### ISSUE TITLE
FlipCheck Function

### ISSUE THREAD

**Issue by andrewsheridan** [andrewsheridan/doubleStuffed#8]

**Comment by laurelstewart** [comment]
Started working on this at 10:15 pm November 11

**Comment by ryan-merrick** [comment]
Laurel, sorry I took this. I'm still figuring out how gitHub and assigning things work. But I believe I've completed at least most of the functions I monkey-programmed in the SDD. It has been submitted, as told by the group Hangouts, currently the second to last and the last posts.
